2024-05-29 12:32:49,834 - cauldron - INFO - -- Cauldron Application --
2024-05-29 12:32:50,218 - cauldron - INFO - Initializing Cauldron Application
2024-05-29 12:32:50,219 - cauldron - INFO - Initializing SQLAgent with model: gpt-4, db_path: sqlite:///sql/recipes_0514_1821.db, verbose: True
2024-05-29 12:32:50,316 - cauldron - INFO - Creating SQL Agent with model: gpt-4 and database: <langchain_community.utilities.sql_database.SQLDatabase object at 0x00000275E97E6DB0>
2024-05-29 12:32:54,367 - cauldron - INFO - SQL Agent created successfully.
2024-05-29 12:32:54,368 - cauldron - INFO - SQLAgent initialized successfully.
2024-05-29 12:32:54,373 - cauldron - INFO - SQL Agent Initialized
2024-05-29 12:32:54,374 - cauldron - INFO - Initializing ChatBot with model: gpt-4, prompt: blake-goodwyn/cauldron-assistant-v0, temperature: 0.0
2024-05-29 12:32:54,374 - cauldron - INFO - Creating chatbot with model: gpt-4, prompt: blake-goodwyn/cauldron-assistant-v0, temperature: 0.0
2024-05-29 12:33:00,544 - cauldron - INFO - Chatbot created successfully.
2024-05-29 12:33:00,545 - cauldron - DEBUG - Creating StrOutputParser instance.
2024-05-29 12:33:00,546 - cauldron - INFO - UI Agent Initialized
2024-05-29 12:33:00,547 - cauldron - INFO - Initializing Interactive Demo Application
2024-05-29 12:33:00,548 - cauldron - INFO - Serial Port and ADC Constants Initialized
2024-05-29 12:33:02,007 - cauldron - INFO - Voice Interface Initialized
2024-05-29 12:33:02,008 - cauldron - INFO - Grid Layout Initialized
2024-05-29 12:33:02,016 - cauldron - INFO - Text Interaction Components Initialized
2024-05-29 12:33:02,018 - cauldron - INFO - Transcription Components Initialized
2024-05-29 12:33:02,023 - cauldron - ERROR - Error opening serial port: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
Traceback (most recent call last):
  File "c:\Users\blake\Documents\GitHub\ebakery\cauldron-app\interactive_demo.py", line 84, in __init__
    self.ser = serial.Serial(self.SERIAL_PORT, self.BAUD_RATE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python312\Lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Python312\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-05-29 12:33:02,033 - cauldron - WARNING - Serial connection could not be established.
2024-05-29 12:33:02,034 - cauldron - INFO - Cauldron Application Initialized
