2024-05-29 18:39:13,639 - cauldron - INFO   - cauldron_app.py - Initializing Cauldron Application
2024-05-29 18:39:13,640 - cauldron - INFO   - langchain_util.py - Creating agent with model: gpt-3.5-turbo, promptRef: ConductorAgent, tools: [Tool(name='Datetime', description='Returns the current datetime', func=<function <lambda> at 0x000002F1969F1A80>)]
2024-05-29 18:39:15,004 - cauldron - ERROR  - langchain_util.py - Unexpected error in createAgent: 'messages'
Traceback (most recent call last):
  File "c:\Users\blake\Documents\GitHub\ebakery\cauldron-app\langchain_util.py", line 72, in createAgent
    prompt = ChatPromptTemplate(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pydantic\v1\main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\pydantic\v1\main.py", line 1048, in validate_model
    input_data = validator(cls_, input_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\langchain_core\prompts\chat.py", line 853, in validate_input_variables
    messages = values["messages"]
               ~~~~~~^^^^^^^^^^^^
KeyError: 'messages'
